spring:
  config:
    import: optional:file:.env[.properties]
  ai:
#    google:
#      genai:
#        api-key: "AIzaSyC9oqywxfKvshzuMxC7CHMmDsRzaXrHvlg"
    openai:
      api-key: ${CLOUDFLARE_API_KEY}
      base-url: "https://api.cloudflare.com/client/v4/accounts/cd780bf0049574704eccbf0c1f5f622b/ai/v1"
      chat:
        options:
#          model: "gemini-3.8-flash"
          model: "@cf/meta/llama-3.1-8b-instruct-fp8"
          max-tokens: 4096
  datasource:
    url: jdbc:postgresql://ep-young-thunder-b46nelsn-pooler.c-6.us-east-2.aws.neon.tech/neondb?sslmode=require
    username: neondb_owner
    password: npg_yo4GWbdI6PUu
    driver-class-name: org.postgresql.Driver
  sql:
    init:
      mode: never
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        physical_naming_strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        jdbc:
          time_zone: Asia/Ho_Chi_Minh
  jackson:
    time-zone: Asia/Ho_Chi_Minh
    date-format: yyyy-MM-dd
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
  data:
    redis:
      host: localhost
      port: 6379
jwt:
  secretKey: "a1Y1ksRv71WUdnPa6RNwqoc4Y5xtminhchiendeptrai"
google:
  clientId: ""

