spring:
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
      - org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration
  ai:
    google:
      genai:
        api-key: "AQ.Ab8RN6JS6b5aLrqG7JSU8lxAKnqwO6XaxCVEMDeNxCjnXY6QDQ"
        chat:
          options:
            model: "gemini-3.8-flash"
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: Minhchien4585!
    driver-class-name: org.postgresql.Driver
  sql:
    init:
      mode: never
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        physical_naming_strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        jdbc:
          time_zone: Asia/Ho_Chi_Minh
  jackson:
    time-zone: Asia/Ho_Chi_Minh
    date-format: yyyy-MM-dd
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
  data:
    redis:
      host: localhost
      port: 6379
jwt:
  secretKey: "a1Y1ksRv71WUdnPa6RNwqoc4Y5xtminhchiendeptrai"
google:
  clientId: ""

